export const ERROR_DETAIL = {
  // COMMON ERROR
  UNKNOWN_ERROR: 'UNKNOWN_ERROR',
  INVALID_INPUT: 'INVALID_INPUT',

  // DB 관련 에러
  ALREADY_EXIST: 'ALREADY_EXIST',
  ALREADY_EXIST_EMAIL: 'ALREADY_EXIST_EMAIL',
  ALREADY_EXIST_NICKNAME: 'ALREADY_EXIST_NICKNAME',
  ALREADY_EXIST_PHONE: 'ALREADY_EXIST_PHONE',

  // 인증 관련 에러
  INVALID_TOKEN: 'INVALID_TOKEN',
  TOKEN_EXPIRED: 'TOKEN_EXPIRED',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
  WRONG_PASSWORD: 'WRONG_PASSWORD',

  // 서버 가용치 한계점을 넘어서는 요청이 들어왔을 때
  RUST_PANIC: 'RUST_PANIC',

  NOT_EXIST: 'NOT_EXIST',
  NOT_ENOUGH_REQ_DATA: 'NOT_ENOUGH_REQ_DATA',
  NOT_MATCH: 'NOT_MATCH',
  NOT_ALLOWED: 'NOT_ALLOWED',
  NOT_AUTHORIZED: 'NOT_AUTHORIZED',
  NOT_VALID: 'NOT_VALID',
  NOT_ACCEPTABLE: 'NOT_ACCEPTABLE',

  // 요청이 구현되지 않았을 때
  NOT_IMPLEMENTED: 'NOT_IMPLEMENTED',

  NOT_FOUND: 'NOT_FOUND',
  NOT_ALLOWED_METHOD: 'NOT_ALLOWED_METHOD',
  NOT_ALLOWED_HEADER: 'NOT_ALLOWED_HEADER',
  NOT_ALLOWED_QUERY: 'NOT_ALLOWED_QUERY',
  NOT_ALLOWED_BODY: 'NOT_ALLOWED_BODY',
  NOT_ALLOWED_PARAM: 'NOT_ALLOWED_PARAM',
  NOT_ALLOWED_COOKIE: 'NOT_ALLOWED_COOKIE',
  NOT_ALLOWED_FILE: 'NOT_ALLOWED_FILE',
  NOT_ALLOWED_REQUEST: 'NOT_ALLOWED_REQUEST',
  NOT_ALLOWED_RESPONSE: 'NOT_ALLOWED_RESPONSE',
  NOT_ALLOWED_STATUS: 'NOT_ALLOWED_STATUS',
  NOT_ALLOWED_CONTENT_TYPE: 'NOT_ALLOWED_CONTENT_TYPE',
  NOT_ALLOWED_CONTENT_LENGTH: 'NOT_ALLOWED_CONTENT_LENGTH',
  NOT_ALLOWED_CONTENT_ENCODING: 'NOT_ALLOWED_CONTENT_ENCODING',
  NOT_ALLOWED_CONTENT_LANGUAGE: 'NOT_ALLOWED_CONTENT_LANGUAGE',
  NOT_ALLOWED_CONTENT_LOCATION: 'NOT_ALLOWED_CONTENT_LOCATION',
  NOT_ALLOWED_CONTENT_RANGE: 'NOT_ALLOWED_CONTENT_RANGE',
  NOT_ALLOWED_CONTENT_MD5: 'NOT_ALLOWED_CONTENT_MD5',
  NOT_ALLOWED_CONTENT_DISPOSITION: 'NOT_ALLOWED_CONTENT_DISPOSITION',
  NOT_ALLOWED_CONTENT_TRANSFER_ENCODING:
    'NOT_ALLOWED_CONTENT_TRANSFER_ENCODING',
} as const

export const HINT_MESSAGE = {
  CHECK_INPUT_DATA: 'CHECK_INPUT_DATA',

  PLEASE_CHECK_THE_APP_STATUS: 'PLEASE_CHECK_THE_APP_STATUS',

  PLEASE_SIGNUP: 'PLEASE_SIGNUP',
  PLEASE_LOGIN: 'PLEASE_LOGIN',
  PLEASE_AGREE_TERMS: 'PLEASE_AGREE_TERMS',

  PLEASE_CHECK_EMAIL: 'PLEASE_CHECK_EMAIL',
  PLEASE_CHECK_PASSWORD: 'PLEASE_CHECK_PASSWORD',
  PLEASE_CHECK_NICKNAME: 'PLEASE_CHECK_NICKNAME',
  PLEASE_CHECK_PHONE: 'PLEASE_CHECK_PHONE',
  PLEASE_CHECK_BIRTHDAY: 'PLEASE_CHECK_BIRTHDAY',

  PLEASE_LOGIN_WITH_OTHER_ACCOUNT: 'PLEASE_LOGIN_WITH_OTHER_ACCOUNT',

  PLEASE_CHECK_TITLE: 'PLEASE_CHECK_TITLE',
  PLEASE_CHECK_CONTENT: 'PLEASE_CHECK_CONTENT',
} as const

export const MESSAGE = {
  // for firebase
  BROADCAST_SUCCESS: 'BROADCAST_SUCCESS',
  BROADCAST_FAIL: 'BROADCAST_FAIL',
  DEVICE_REGISTER_SUCCESS: 'DEVICE_REGISTER_SUCCESS',
  DEVICE_DELETE_SUCCESS: 'DEVICE_DELETE_SUCCESS',
  DEVICE_REGISTER_FAIL: 'DEVICE_REGISTER_FAIL',
  DEVICE_DELETE_FAIL: 'DEVICE_DELETE_FAIL',

  // COMMON MESSAGE
  FORBIDDEN: 'FORBIDDEN',
  INVALID_INPUT: 'INVALID_INPUT',
  UNAUTHORIZED: 'UNAUTHORIZED',
  NOT_FOUND: 'NOT_FOUND',
  PRISMA_ERROR: 'PRISMA_ERROR',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  BAD_REQUEST: 'BAD_REQUEST',
  SERVER_ERROR: 'SERVER_ERROR',

  // SUCCESS MESSAGE
  SUCCESS: 'SUCCESS',
  REFRESH_TOKEN_SUCCESS: 'REFRESH_TOKEN_SUCCESS',
  VALIDATE_SUCCESS: 'VALIDATE_SUCCESS',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  SIGNUP_SUCCESS: 'SIGNUP_SUCCESS',
  PROFILE_UPDATE_REQUEST_CREATED: 'PROFILE_UPDATE_REQUEST_CREATED',
  PROFILE_UPDATE_REQUEST_UPDATED: 'PROFILE_UPDATE_REQUEST_UPDATED',

  // 인증 (1. 패스 인증)
  VERIFY_SUCCESS: 'VERIFY_SUCCESS',
  VERIFY_FAILED: 'VERIFY_FAILED',

  CREATED_SUCCESS: 'CREATED_SUCCESS',
  READ_SUCCESS: 'READ_SUCCESS',
  UPDATED_SUCCESS: 'UPDATED_SUCCESS',
  DELETED_SUCCESS: 'DELETED_SUCCESS',
  REFRESH_SUCCESS: 'REFRESH_SUCCESS',

  // PASS AUTHENTICATION MESSAGE
  PASS_AUTHENTICATION_SUCCESS: 'PASS_AUTHENTICATION_SUCCESS',
  PASS_AUTHENTICATION_FAILED: 'PASS_AUTHENTICATION_FAILED',
  PASS_AUTHENTICATION_ERROR: 'PASS_AUTHENTICATION_ERROR',

  // FAIL MESSAGE
  FAIL: 'FAIL',
  VALIDATE_FAIL: 'VALIDATE_FAIL',
  LOGIN_FAIL: 'LOGIN_FAIL',
  LOGOUT_FAIL: 'LOGOUT_FAIL',
  SIGNUP_FAIL: 'SIGNUP_FAIL',
  INVALID_TOKEN: 'INVALID_TOKEN',
  PROFILE_UPDATE_REQUEST_CREATE_FAILED: 'PROFILE_UPDATE_REQUEST_CREATE_FAILED',
  PROFILE_UPDATE_REQUEST_UPDATE_FAILED: 'PROFILE_UPDATE_REQUEST_UPDATE_FAILED',

  CREATE_FAIL: 'CREATE_FAIL',
  READ_FAIL: 'READ_FAIL',
  UPDATE_FAIL: 'UPDATE_FAIL',
  DELETE_FAIL: 'DELETE_FAIL',

  NEED_TO_SIGNUP: 'NEED_TO_SIGNUP',
  TERMS_AGREEMENT_REQUIRED: 'TERMS_AGREEMENT_REQUIRED',

  // LOGIN OR SIGNUP MESSAGE
  SUCCESS_TO_LOGIN: 'SUCCESS_TO_LOGIN',
  SUCCESS_TO_FIND: 'SUCCESS_TO_FIND',
  WRONG_PASSWORD: 'WRONG_PASSWORD',
  FAIL_TO_LOGIN: 'FAIL_TO_LOGIN',
  ALREADY_EXIST: 'ALREADY_EXIST',
  SUCCESS_TO_SIGNUP: 'SUCCESS_TO_SIGNUP',
  NEED_TO_AGREE_TERMS: 'NEED_TO_AGREE_TERMS',
  NOT_ENOUGH_PROFILE: 'NOT_ENOUGH_PROFILE',
  NEED_TO_SET_NICKNAME: 'NEED_TO_SET_NICKNAME',

  // USER MESSAGE
  SUCCESS_TO_GET_USER_LIST: 'SUCCESS_TO_GET_USER_LIST',
  FAILED_TO_GET_USER_LIST: 'FAILED_TO_GET_USER_LIST',
  USER_NOT_FOUND: 'USER_NOT_FOUND',
} as const
